### PR TITLE
Use new folders manifest field

### PR DESCRIPTION
**Pull request by CPatchane**
Related to https://github.com/cozy/cozy-apps-registry/pull/18 which add documentation about this new property

### CODE REVIEW

**Comment by CPatchane** [comment]
@kosssi The tests failed here since konitor need the `fields` property which is not mandatory now with this folders property

**Comment by CPatchane** [comment]
@doubleface The registry PR is just about documentation, but we may to update cozy-stack to handle this new property

**Comment by doubleface** [comment]
@CPatchane @kosssi Here is the related PR in konitor : https://github.com/konnectors/konitor/pull/153

**Comment by CPatchane** [comment]
@doubleface I upgraded konitor with the last version with your changes

**Pull request merged**
